on:
  # on any push to the repository
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    # multiple python versions
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox twine build
      # run tox to run the tests
      - name: Run tests
        run: tox
      # build the package
      - name: Build package
        run: python -m build
      # run twine to check the package
      - name: Check package
        run: twine check dist/*
